### ISSUE TITLE
Why is't it a derive macro?

### ISSUE THREAD

**Issue by vi** [Juici/int-enum-rs#1]
Why it is not `#[derive(int_enum::int_enum)]` instead of `#[int_enum::int_enum]`? Does it require feature inaccessible to derive macros?

**Comment by Juici** [comment]
The syntax is `#[int_enum::int_enum(u8)` where `u8` can be replaced with any primitive integer type. When I first wrote the library I wasn't aware I could use a derive macro to achieve the result I was after.

I could change the macro into a derive macro with this style of syntax.

```rust
#[derive(IntEnum)]
#[repr(u8)]
enum Number {
	One = 1,
	Two = 2,
}
```

Where the `repr` is used for the integer representation for the enum. This would also mean that the memory layout used by the enum would be the same as that of the integer.

This is an option and I may well update the macro with this syntax, if you have a use case where this would be preferable I can certainly add support for it.

If I did add support for the derive syntax, I would likely deprecate the current macro due to an attribute macro being overkill for the goal of the library.

**Comment by Juici** [comment]
I've started working on this here https://github.com/Juici/int-enum-rs/commit/3c4f73252c0fb75126e6b7185fb9b0476f0e9b62.

**Comment by Juici** [comment]
Switched to a derive macro in [0.4.0](https://github.com/Juici/int-enum-rs/releases/tag/0.4.0).
